### ISSUE TITLE
init-pants - getting "gh: Not Found (HTTP 404)"

### ISSUE THREAD

**Issue by ZdenekM** [pantsbuild/actions#15]
Tried to figure out why init-pants action does not work for me... According to https://stackoverflow.com/a/73011420/3142796, there should not be `/` in front of `repos`. Could this be the problem?

The result I'm getting: https://github.com/robofit/arcor2/actions/runs/4022974520/jobs/6913303946#step:6:96

**Comment by benjyw** [comment]
Oh, interesting, good find!

@cognifloyd , I assume you tested the CACHECOMMIT stuff with the URL as-is and it worked? Maybe this is sensitive to `gh` version or something.

@ZdenekM would you be able to test your hypothesis by copying that `gh api` command into a step directly in your CI (early enough that it's before this failure, of course, or you can temporarily remove the init-pants step, since we only care about running that `gh api` command, everything after it can fail) verifying that it fails, and then verifying that it succeeds if you remove the slash?

**Comment by cognifloyd** [comment]
Yes. I've used the initial `/` for awhile in a variety of projects. That's good to know we can drop it. I'm surprised it didn't work.

**Comment by ZdenekM** [comment]
Ok, it seems that the problem is somewhere else. Sorry for the noise :-)

![Snímek obrazovky pořízený 2023-02-02 08-12-25](https://user-images.githubusercontent.com/1199396/216256496-25a572e0-4c68-4668-8354-07f0a0e25ee8.png)
![Snímek obrazovky pořízený 2023-02-02 08-10-57](https://user-images.githubusercontent.com/1199396/216256498-c0895282-a568-4d1d-b671-70ab966f84e2.png)

**Comment by ZdenekM** [comment]
Hmm, maybe some issue with `GITHUB_TOKEN` permissions? I think I haven't changed anything from the defaults...

![Snímek obrazovky pořízený 2023-02-02 08-31-09](https://user-images.githubusercontent.com/1199396/216259849-72db1bbc-d592-4de1-b156-a7adcb17eb5d.png)

**Comment by benjyw** [comment]
read permissions should be enough, so I doubt that's it.

**Comment by cognifloyd** [comment]
Your main branch is master not main, so you need to pass that in the parameter: `base-branch=master`

**Comment by ZdenekM** [comment]
@cognifloyd Yep, that was it! Thanks...
